### PR TITLE
refactor: remove `es-iterator-helpers` dependency

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
This dep is still needed until node 20 is dropped.

**Comment by MichaelDeBoey** [comment]
@ljharb Can you explain why?

`aria-query` returns normal arrays as of v5 for all `*.keys()` & `*.values()`, so we don't need iterator helpers and can just use built-in array functionality?
https://github.com/A11yance/aria-query/blob/main/CHANGELOG.md#500

**Comment by ljharb** [comment]
aha, you're right. in that case, this PR should be able to go to `main` instead of `breaking`, yes?

**Comment by MichaelDeBoey** [comment]
@ljharb Those array functions didn't exist on Node v4 yet, so we can't merge this PR to `main`

**Comment by ljharb** [comment]
True. but on `main` we could replace the iterator helpers with array method packages?

**Comment by MichaelDeBoey** [comment]
That would indeed be possible, but that would mean that we need to do 2 PRs: 1 on `main` to use array method packages + 1 on `breaking` to remove those packages as well and do what I did in this PR

**Comment by ljharb** [comment]
True. It'd be nice to have both tho :-) also likely the next time i rebase `breaking` i'll be removing all the relevant array dep usages you add anyways

**Comment by MichaelDeBoey** [comment]
@ljharb #1020 is already removing all these array function package usages, so I'd rather keep working on `breaking` to move forward asap tbh

**Review by ljharb — APPROVED** [review]

**Pull request merged**
