### PR TITLE
Doc how disabled click-events-have-key-events

### PR DESCRIPTION
**Pull request by enBonnet**

### CODE REVIEW

**Comment by ljharb** [comment]
This is how you disable every eslint rule; is there a reason it needs to be added to this one rule doc?

**Comment by enBonnet** [comment]
I think every rule must document itself, cuz if i'm working with it and come here to documentation searching how to disabled this rule, will need to find in eslint docs.
Could be confused for developers on learning path, just and opinion, sorry about my english :-D

**Comment by ljharb** [comment]
eslint plugin docs tend to assume you understand the basics of eslint, since presumably you read eslint's docs before trying to use a plugin.

**Comment by enBonnet** [comment]
in that scenery this PR could be closed, thanks you for comment me

**Comment by ljharb** [comment]
No problem, thanks for the contribution anyways!

**Pull request closed without merging**
