### PR TITLE
feat: Support ESLint 7.x

### LINKED ISSUE #683: Support ESLint 7.x
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

(dev)Dependencies should be compatible with ESLint 7 too before we can merge this one:

- [ ] [`jsx-ast-utils`](https://github.com/evcohen/jsx-ast-utils/issues/96)
  - [ ]  [PR](https://github.com/evcohen/jsx-ast-utils/pull/100)
  - [ ]  Released
- [x] [`eslint-config-airbnb-base`](https://github.com/airbnb/javascript/issues/2223)
  - [x]  [PR](https://github.com/airbnb/javascript/pull/2240)
  - [x]  [Release](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md#1420--2020-06-10)
- [x] [`eslint-plugin-flowtype`](https://github.com/gajus/eslint-plugin-flowtype/issues/446)
  - [x]  [PR](https://github.com/gajus/eslint-plugin-flowtype/pull/447)
  - [x]  [Release](https://github.com/gajus/eslint-plugin-flowtype/releases/tag/v5.0.0)
- [x] [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import/issues/1772)
  - [x]  [PR](https://github.com/benmosher/eslint-plugin-import/pull/1715) + [commit](https://github.com/benmosher/eslint-plugin-import/commit/6a110dd16a7fd775f08601054bf14ffd503eea7b)
  - [x]  [Release](https://github.com/benmosher/eslint-plugin-import/blob/master/CHANGELOG.md#2211---2020-06-07)

---

Closes #683

### CODE REVIEW

**Comment by ljharb** [comment]
updating jsx-ast-utils is not required to release this PR, since it just uses eslint as a dev dep.

**Comment by MichaelDeBoey** [comment]
> updating jsx-ast-utils is not required to release this PR

@ljharb It does, since `jsx-ast-utils` is a dependency of this package, which is using `node.start` and that breaks ESLint 7 compatibility.

**Comment by weyert** [comment]
Anyway to get this PR progressing? Love to use this plugin with ESLint 7 :)

**Comment by jessebeach** [comment]
@MichaelDeBoey thank you so much for this contribution. We'll get this in as soon as it is ready.

**Comment by ljharb** [comment]
`eslint-config-airbnb-base` has been updated and I've rebased this PR. Tests are indeed failing, so it looks like we'll need the [jsx-ast-utils update](https://github.com/jsx-eslint/jsx-ast-utils/pull/97) before proceeding.

**Comment by ljharb** [comment]
rebased again with the latest jsx-ast-utils published

**Comment by ljharb** [comment]
It's failing because jsx-ast-utils is still using `.start` in at least one place. No need to update this PR please; I'll update jsx-ast-utils, and then rebase this PR once that's done :-)

**Comment by ljharb** [comment]
@jessebeach are you working on a release soon, or should i cut one?

**Comment by danez** [comment]
Can we please have a release?

**Comment by ljharb** [comment]
@jessebeach i can get you any npm privileges you need; lmk if there's an issue.

**Pull request merged**
