### PR TITLE
[Tests] `label-has-associated-control`: add additional test cases

### LINKED ISSUE #962: label-has-associated-control regression
Looks like `controlComponents` option is no longer respected.

The following code now gives `A form label must be associated with a control` warning:

```jsx
/* eslint
  "jsx-a11y/label-has-associated-control": [
    "error", { "controlComponents": ["InputComponent"] },
  ],
*/

function MyComponent() {
  return (
    <label>
      My label
      <InputComponent />
    </label>
  );
}
```

Started happening after upgrade from 6.7.1 to 6.8.0.

### PR DESCRIPTION
**Pull request by lb-**
- Add test cases for non-nested labels with custom `controlComponents`
- Fix small typo in mayContainChildComponent util
- Closes #962

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Thanks!

**Comment by lb-** [comment]
Should I be doing something about the failed tests? It does not seem related to this PR change. @ljharb 

> Error: Could not find file '/home/runner/work/_actions/_temp_037dfe23-6e26-4231-a930-59738e4e581c/_staging/ljharb-actions-790263f/node_modules/@npmcli/package-json/node_modules/.bin/glob'.

**Comment by ljharb** [comment]
Nope! I'll rerun the failing ones; was a now-reverted bug in one of the actions we use.

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by lb-** [comment]
Thanks for reviewing and merging.

**Pull request merged**
