### PR TITLE
[New] `interactive-supports-focus`: add basic suggestions 

### LINKED ISSUE #952: [feature] suggest tabindex 0 or -1 for interactive-supports-focus
When `interactive-supports-focus` fails, the only reasonable solution is to add a `tabindex` of either `0` or `-1`.

Modify `interactive-supports-focus` to have `hasSuggestions: true` with a `suggest` array with 2 entries for fixing to 0 or -1.

Related to #951

### PR DESCRIPTION
**Pull request by lb-**
Add basic support for ESlint rule suggestions for the `interactive-supports-focus` for tabIndex values when elements are interactive but do not have implicit focusable browser behaviour. These are intentionally not auto-fix but simply optional suggestions to help developers resolve their issue.

Fixes #952
See also #951

Implementation as per ESlint documentation https://eslint.org/docs/latest/extend/custom-rules#providing-suggestions
Tests added as per ESlint documentation https://eslint.org/docs/latest/integrate/nodejs-api#testing-suggestions

## Screenshots of editor suggestions (npm link testing)

Screenshot 2024-10-23 at 12 10 35 PM
Screenshot 2024-10-23 at 12 10 15 PM

**Before**

```tsx
<div onClick={(event) => console.log(event)} role="menu">Click</div>
```

**After**
```tsx
<div tabIndex={-1} onClick={(event) => console.log(event)} role="menu">Click</div>
```

### CODE REVIEW

**Comment by lb-** [comment]
Checking all tests pass & fixing if there are issues. After that I will mark as ready for review.

**Comment by lb-** [comment]
Ready for review.

**Review by ckundo — APPROVED** [review]
Awesome!

**Review by ljharb — APPROVED** [review]

**Comment by lb-** [comment]
Thank you for reviewing. @ljharb

**Pull request merged**
